alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.company_members add column if not exists role text not null default 'MEMBER';
alter table public.company_members add column if not exists status text not null default 'ACTIVE';
alter table public.company_members add column if not exists created_at timestamptz not null default now();
alter table public.teams add column if not exists created_at timestamptz not null default now();
alter table public.projects add column if not exists project_code text;
alter table public.projects add column if not exists client_name text;
alter table public.projects add column if not exists location text;
alter table public.projects add column if not exists start_date date;
alter table public.projects add column if not exists due_date date;
alter table public.projects add column if not exists notes text;
alter table public.projects add column if not exists updated_at timestamptz not null default now();
alter table public.systems add column if not exists name text;
alter table public.systems add column if not exists status text not null default 'PLANNED';
alter table public.systems add column if not exists notes text;
alter table public.systems add column if not exists created_at timestamptz not null default now();
alter table public.systems add column if not exists updated_at timestamptz not null default now();
alter table public.tasks add column if not exists system_id uuid references public.systems(id) on delete set null;
alter table public.tasks add column if not exists assigned_to uuid references public.profiles(id) on delete set null;
alter table public.tasks add column if not exists due_date date;
alter table public.tasks add column if not exists notes text;
alter table public.materials add column if not exists sku text;
alter table public.materials add column if not exists stock_quantity numeric not null default 0;
alter table public.materials add column if not exists min_stock_quantity numeric not null default 0;
alter table public.materials add column if not exists average_price numeric not null default 0;
alter table public.materials add column if not exists updated_at timestamptz not null default now();
alter table public.tool_requests add column if not exists title text;
alter table public.tool_requests add column if not exists description text;
alter table public.tool_requests add column if not exists status text not null default 'REQUESTED';
alter table public.tool_requests add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.tool_requests add column if not exists updated_at timestamptz not null default now();
alter table public.procurements add column if not exists title text;
alter table public.procurements add column if not exists project_id uuid references public.projects(id) on delete set null;
alter table public.procurements add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.procurements add column if not exists updated_at timestamptz not null default now();
alter table public.documents add column if not exists document_type text;
alter table public.documents add column if not exists ai_summary text;
alter table public.documents add column if not exists ai_fields jsonb not null default '{}'::jsonb;
do $$
begin
if exists (select 1 from information_schema.columns where table_schema='public' and table_name='materials' and column_name='quantity') then
execute 'update public.materials set stock_quantity = quantity where stock_quantity = 0 and quantity is not null';
end if;
if exists (select 1 from information_schema.columns where table_schema='public' and table_name='materials' and column_name='minimum') then
execute 'update public.materials set min_stock_quantity = minimum where min_stock_quantity = 0 and minimum is not null';
end if;
if exists (select 1 from information_schema.columns where table_schema='public' and table_name='tool_requests' and column_name='raw_text') then
execute 'update public.tool_requests set title = raw_text where title is null';
end if;
end $$;
update public.tool_requests set title = 'Szerszámigény' where title is null;
update public.procurements set title = 'Beszerzés' where title is null;
alter table public.projects drop constraint if exists projects_progress_check;
alter table public.projects add constraint projects_progress_check check (progress between 0 and 100) not valid;
alter table public.projects validate constraint projects_progress_check;
alter table public.systems drop constraint if exists systems_progress_check;
alter table public.systems add constraint systems_progress_check check (progress between 0 and 100) not valid;
alter table public.systems validate constraint systems_progress_check;
alter table public.tasks drop constraint if exists tasks_progress_check;
alter table public.tasks add constraint tasks_progress_check check (progress between 0 and 100) not valid;
alter table public.tasks validate constraint tasks_progress_check;
create index if not exists company_members_user_idx on public.company_members(user_id, status);
create index if not exists projects_company_active_idx on public.projects(company_id, active);
create index if not exists systems_project_idx on public.systems(project_id);
create index if not exists tasks_company_status_idx on public.tasks(company_id, status, due_date);
create index if not exists materials_company_stock_idx on public.materials(company_id, stock_quantity);
create index if not exists work_logs_company_date_idx on public.work_logs(company_id, work_date desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, company_id, read_at);
create index if not exists audit_events_company_created_idx on public.audit_events(company_id, created_at desc);
create index if not exists invoices_company_status_idx on public.invoices(company_id, status, due_date);
